<!doctype html>
<html lang="en">
<head><link rel="icon" type="image/png" href="{{ asset('favicon.png') }}">
    <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ $gallery->name }} — Photo selection</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet">
    <style>body{background:#f7f7f9;color:#171520}.proof-head{background:linear-gradient(135deg,#171229,#35205b);color:#fff}.proof-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:10px}.proof{position:relative;background:#fff;border:3px solid transparent;border-radius:13px;overflow:hidden}.proof.selected{border-color:#dc3545;box-shadow:0 0 0 2px #dc354522}.proof img{width:100%;aspect-ratio:1;object-fit:cover;cursor:zoom-in}.proof button{position:absolute;right:8px;bottom:8px;border:0;border-radius:999px;padding:8px 12px;background:#fff;font-weight:700;box-shadow:0 3px 14px #0003}.proof.selected button{background:#dc3545;color:#fff}.proof small{position:absolute;left:7px;bottom:8px;max-width:55%;padding:4px 7px;border-radius:6px;background:#0009;color:#fff;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.selection-bar{position:sticky;z-index:50;bottom:12px;display:flex;align-items:center;justify-content:space-between;gap:15px;margin:25px auto;padding:12px 15px;border-radius:15px;background:#171229;color:#fff;box-shadow:0 12px 35px #17122966}.preview-nav{position:absolute;top:50%;transform:translateY(-50%);z-index:2;border:0;border-radius:50%;width:48px;height:48px;background:#fff;color:#111}.preview-prev{left:12px}.preview-next{right:12px}@media(max-width:600px){.proof-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:6px}.proof button{font-size:.72rem;padding:7px 9px}.proof small{font-size:.66rem}.selection-bar{bottom:6px;margin-bottom:8px}.selection-bar small{display:none}.selection-bar .btn{font-size:.85rem}.preview-nav{width:40px;height:40px}}</style>
</head><body>
<header class="proof-head py-5"><div class="container">@if($gallery->business->logo_path)<img src="{{ route('public.business.logo',$gallery->business->slug) }}" style="max-width:100px;max-height:55px" class="mb-3" alt="{{ $gallery->business->name }} logo">@endif<p class="text-white-50 mb-1">{{ $gallery->business->name }}</p><h1>{{ $gallery->name }}</h1><p class="mb-1">{{ $gallery->event }} @if($gallery->event_date) · {{ $gallery->event_date->format('F j, Y') }}@endif</p><p class="text-white-50 mb-0">{{ $gallery->description ?: 'Choose the photos you would like us to professionally edit.' }}</p></div></header>
<main class="container py-4">
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
@if($gallery->selection_completed_at)<div class="alert alert-success p-4"><h2 class="h4">Selection submitted successfully</h2><p class="mb-0">{{ $gallery->submitted_selection_count }} photos have been sent to your photographer. Your selection is locked while editing begins.</p></div>@endif
<div class="d-flex justify-content-between align-items-end gap-3 mb-3"><div><b>{{ $photos->total() }} proof photos</b><small class="d-block text-muted">Tap a photo for a larger preview.</small></div><b id="top-count" class="text-danger text-nowrap">Selected: {{ $selectedPhotoIds->count() }} / {{ $gallery->selection_limit ?: '∞' }}</b></div>
<div class="proof-grid">@foreach($photos as $photo)<article class="proof {{ $selectedPhotoIds->contains($photo->id)?'selected':'' }}" data-id="{{ $photo->id }}" data-name="{{ $photo->filename }}"><img loading="lazy" src="{{ route('selection.image',[$token,$photo]) }}" alt="{{ $photo->filename }}" onclick="openPreview(this)"><small>{{ $loop->iteration + (($photos->currentPage()-1)*$photos->perPage()) }} · {{ $photo->filename }}</small><button type="button" @disabled($gallery->selection_completed_at) onclick="togglePhoto(this)">{{ $selectedPhotoIds->contains($photo->id)?'✓ Selected':'Select' }}</button></article>@endforeach</div>{{ $photos->links() }}
@unless($gallery->selection_completed_at)<form method="POST" action="{{ route('selection.submit',$token) }}" class="selection-bar" onsubmit="return confirmSubmit()">@csrf<span><strong><b id="count">{{ $selectedPhotoIds->count() }}</b> / {{ $gallery->selection_limit ?: '∞' }} selected</strong><small class="d-block text-white-50">Progress saves automatically</small></span><button class="btn btn-danger" id="submit" @disabled($selectedPhotoIds->isEmpty())>Submit selection</button></form>@endunless
</main>
<div class="modal fade" id="preview" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-centered"><div class="modal-content bg-dark"><div class="modal-body text-center p-0"><img id="preview-image" class="img-fluid" style="max-height:88vh" alt=""><div id="preview-name" class="position-absolute bottom-0 start-50 translate-middle-x bg-dark bg-opacity-75 px-3 py-2 rounded-top"></div><button class="preview-nav preview-prev" type="button" onclick="movePreview(-1)" aria-label="Previous photo"><i class="bi bi-chevron-left"></i></button><button class="preview-nav preview-next" type="button" onclick="movePreview(1)" aria-label="Next photo"><i class="bi bi-chevron-right"></i></button><button class="btn-close btn-close-white position-absolute top-0 end-0 m-3" data-bs-dismiss="modal" aria-label="Close"></button></div></div></div></div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script>const cards=[...document.querySelectorAll('.proof')];let previewIndex=0,count={{ $selectedPhotoIds->count() }},limit=@json($gallery->selection_limit);async function togglePhoto(button){button.disabled=true;const card=button.closest('.proof');try{const response=await fetch(`{{ url('/select/'.$token.'/photos') }}/${card.dataset.id}`,{method:'POST',headers:{'X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content,'Accept':'application/json'}});const json=await response.json();if(!response.ok){const first=Object.values(json.errors||{})[0];throw new Error(json.message||(Array.isArray(first)?first[0]:first)||'Unable to update selection.')}count=json.count;card.classList.toggle('selected',json.selected);button.textContent=json.selected?'✓ Selected':'Select';document.getElementById('count').textContent=count;document.getElementById('top-count').textContent=`Selected: ${count} / ${limit??'∞'}`;document.getElementById('submit').disabled=count===0}catch(error){alert(error.message)}finally{button.disabled=false}}function confirmSubmit(){if(limit&&count<limit&&!confirm(`You selected ${count} of ${limit} available photos. Submit ${count} photos anyway?`))return false;return confirm(`Send your ${count} selected photos to the photographer for editing?`)}function displayPreview(){const card=cards[previewIndex],img=card.querySelector('img'),target=document.getElementById('preview-image');target.src=img.src;target.alt=img.alt;document.getElementById('preview-name').textContent=`${previewIndex+1} / ${cards.length} · ${card.dataset.name}`}function openPreview(img){previewIndex=cards.indexOf(img.closest('.proof'));displayPreview();bootstrap.Modal.getOrCreateInstance(document.getElementById('preview')).show()}function movePreview(step){previewIndex=(previewIndex+step+cards.length)%cards.length;displayPreview()}document.addEventListener('keydown',event=>{if(!document.getElementById('preview').classList.contains('show'))return;if(event.key==='ArrowLeft')movePreview(-1);if(event.key==='ArrowRight')movePreview(1)});</script></body></html>
