<?php

use App\Http\Controllers\ActivityController;
use App\Http\Controllers\AdminBusinessController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BookingController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DocumentController;
use App\Http\Controllers\EquipmentController;
use App\Http\Controllers\ExpenseController;
use App\Http\Controllers\FinalDeliveryController;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\GalleryWorkflowController;
use App\Http\Controllers\GuestSelectionController;
use App\Http\Controllers\ImpersonationController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\LeadController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\OperationsController;
use App\Http\Controllers\PackageController;
use App\Http\Controllers\PasswordController;
use App\Http\Controllers\PortalController;
use App\Http\Controllers\PortfolioController;
use App\Http\Controllers\PublicBusinessController;
use App\Http\Controllers\PublicGalleryController;
use App\Http\Controllers\QuotationController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\ShootController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\SuperAdminController;
use App\Http\Controllers\SupportController;
use App\Http\Controllers\TaskController;
use App\Models\Customer;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    if (! auth()->check()) {
        return view('welcome');
    }
    if (auth()->user()->is_super_admin) {
        return redirect()->route('admin.index');
    }
    if (Customer::where('user_id', auth()->id())->exists()) {
        return redirect()->route('portal.index');
    }

    return redirect()->route('dashboard');
})->name('home');
Route::middleware('guest')->group(function () {
    Route::get('/login', [AuthController::class, 'loginForm'])->name('login');
    Route::post('/login', [AuthController::class, 'login'])->middleware('throttle:6,1');
    Route::get('/register', [AuthController::class, 'registerForm'])->name('register');
    Route::post('/register', [AuthController::class, 'register'])->middleware('throttle:4,1');
    Route::get('/forgot-password', [PasswordController::class, 'request'])->name('password.request');
    Route::post('/forgot-password', [PasswordController::class, 'email'])->name('password.email')->middleware('throttle:3,1');
    Route::get('/reset-password/{token}', [PasswordController::class, 'reset'])->name('password.reset');
    Route::post('/reset-password', [PasswordController::class, 'update'])->name('password.update');
});
Route::post('/logout', [AuthController::class, 'logout'])->middleware('auth')->name('logout');
Route::post('/admin/businesses/{business}/view-as-owner', [ImpersonationController::class, 'start'])->middleware('auth')->name('admin.impersonation.start');
Route::post('/admin/impersonation/stop', [ImpersonationController::class, 'stop'])->middleware('auth')->name('admin.impersonation.stop');
Route::put('/account/password', [PasswordController::class, 'change'])->middleware('auth')->name('account.password');
Route::middleware('auth')->prefix('portal')->name('portal.')->group(function () {
    Route::get('/', [PortalController::class, 'index'])->name('index');
    Route::post('/messages', [PortalController::class, 'message'])->name('message');
    Route::post('/reviews', [PortalController::class, 'review'])->name('review');
    Route::post('/contracts/{contract}/accept', [PortalController::class, 'accept'])->name('contracts.accept');
    Route::get('/invoices/{invoice}/pdf', [PortalController::class, 'invoicePdf'])->name('invoices.pdf');
    Route::get('/quotations/{quotation}/pdf', [PortalController::class, 'quotationPdf'])->name('quotations.pdf');
    Route::get('/receipts/{receipt}/pdf', [PortalController::class, 'receiptPdf'])->name('receipts.pdf');
});
Route::get('/gallery/{code}', [PublicGalleryController::class, 'show'])->name('public.gallery')->middleware('throttle:customer-gallery-120');
Route::get('/select/{token}', [GuestSelectionController::class, 'show'])->name('selection.show')->middleware('throttle:customer-gallery-240');
Route::post('/select/{token}/pin', [GuestSelectionController::class, 'unlock'])->name('selection.unlock')->middleware('throttle:customer-gallery-8');
Route::get('/select/{token}/photos/{photo}', [GuestSelectionController::class, 'image'])->name('selection.image')->middleware('throttle:customer-gallery-300');
Route::post('/select/{token}/photos/{photo}', [GuestSelectionController::class, 'toggle'])->name('selection.toggle')->middleware('throttle:customer-gallery-180');
Route::post('/select/{token}/submit', [GuestSelectionController::class, 'submit'])->name('selection.submit')->middleware('throttle:customer-gallery-10');
Route::get('/delivery/{token}', [FinalDeliveryController::class, 'show'])->name('delivery.show')->middleware('throttle:customer-gallery-240');
Route::get('/delivery/{token}/photos/{photo}', [FinalDeliveryController::class, 'image'])->name('delivery.image')->middleware('throttle:customer-gallery-300');
Route::get('/delivery/{token}/photos/{photo}/download', [FinalDeliveryController::class, 'download'])->name('delivery.download')->middleware('throttle:customer-gallery-120');
Route::post('/delivery/{token}/download', [FinalDeliveryController::class, 'zip'])->name('delivery.zip')->middleware('throttle:customer-gallery-15');
Route::get('/p/{slug}', [PublicBusinessController::class, 'show'])->name('public.business');
Route::get('/p/{slug}/logo', [PublicBusinessController::class, 'logo'])->name('public.business.logo');
Route::get('/p/{slug}/portfolio/{photo}', [PublicBusinessController::class, 'photo'])->name('public.business.photo')->middleware('throttle:240,1');
Route::post('/p/{slug}/book', [PublicBusinessController::class, 'book'])->name('public.business.book')->middleware('throttle:5,1');
Route::post('/gallery/{code}/unlock', [PublicGalleryController::class, 'unlock'])->name('public.gallery.unlock')->middleware('throttle:customer-gallery-10');
Route::get('/gallery/{code}/photo/{photo}', [PublicGalleryController::class, 'image'])->name('public.gallery.photo')->middleware('throttle:customer-gallery-240');
Route::get('/gallery/{code}/photo/{photo}/download', [PublicGalleryController::class, 'download'])->name('public.gallery.download')->middleware('throttle:customer-gallery-60');
Route::post('/gallery/{code}/download', [PublicGalleryController::class, 'zip'])->name('public.gallery.zip')->middleware('throttle:customer-gallery-10');
Route::post('/gallery/{code}/download-all', [PublicGalleryController::class, 'zipAll'])->name('public.gallery.zip-all')->middleware('throttle:customer-gallery-5');
Route::post('/gallery/{code}/photo/{photo}/select', [PublicGalleryController::class, 'select'])->name('public.gallery.select')->middleware('throttle:customer-gallery-120');
Route::post('/gallery/{code}/selection/complete', [PublicGalleryController::class, 'completeSelection'])->name('public.gallery.selection.complete')->middleware('throttle:customer-gallery-10');
Route::post('/gallery/{code}/photo/{photo}/favorite', [PublicGalleryController::class, 'favorite'])->name('public.gallery.favorite')->middleware('throttle:customer-gallery-120');
Route::post('/gallery/{code}/orders', [PublicGalleryController::class, 'order'])->name('public.gallery.order')->middleware('throttle:customer-gallery-20');
Route::get('/gallery/{code}/orders/{order}', [PublicGalleryController::class, 'orderShow'])->name('public.order')->middleware('throttle:customer-gallery-60');
Route::middleware(['auth', 'business', 'impersonation.readonly'])->group(function () {
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::get('sync', [\App\Http\Controllers\SyncController::class, 'index'])->name('sync.index')->middleware('permission:galleries.view');
    Route::post('sync/connection', [\App\Http\Controllers\SyncController::class, 'connection'])->name('sync.connection')->middleware('permission:galleries.manage');
    Route::post('galleries/{gallery}/sync', [\App\Http\Controllers\SyncController::class, 'action'])->name('sync.action')->middleware('permission:galleries.manage');
    Route::get('/search', SearchController::class)->name('search');
    Route::get('/activity', ActivityController::class)->name('activity.index')->middleware('permission:settings.manage');
    Route::resource('customers', CustomerController::class)->middleware('permission:customers.view');
    Route::resource('leads', LeadController::class)->except('show')->middleware('permission:customers.view');
    Route::post('leads/{lead}/convert', [LeadController::class, 'convert'])->name('leads.convert')->middleware('permission:customers.manage');
    Route::resource('packages', PackageController::class)->except('show')->middleware('permission:settings.manage');
    Route::resource('staff', StaffController::class)->only(['index', 'create', 'store', 'edit', 'update'])->middleware('permission:staff.view');
    Route::resource('bookings', BookingController::class)->except('destroy')->middleware('permission:bookings.view');
    Route::post('bookings/{booking}/shoot', [BookingController::class, 'convert'])->name('bookings.shoot')->middleware('permission:bookings.manage');
    Route::resource('shoots', ShootController::class)->only(['index', 'show', 'update'])->middleware('permission:bookings.view');
    Route::get('calendar', [BookingController::class, 'calendar'])->name('calendar')->middleware('permission:bookings.view');
    Route::resource('equipment', EquipmentController::class)->except('destroy')->middleware('permission:staff.manage');
    Route::post('equipment/{equipment}/maintenance', [EquipmentController::class, 'maintenance'])->name('equipment.maintenance')->middleware('permission:staff.manage');
    Route::post('equipment/{equipment}/assign', [EquipmentController::class, 'assign'])->name('equipment.assign')->middleware('permission:staff.manage');
    Route::patch('equipment/{equipment}/assignments/{assignment}/return', [EquipmentController::class, 'returnAssignment'])->name('equipment.return')->middleware('permission:staff.manage');
    Route::resource('invoices', InvoiceController::class)->only(['index', 'create', 'store', 'show'])->middleware('permission:finance.view');
    Route::post('invoices/{invoice}/payments', [InvoiceController::class, 'payment'])->name('invoices.payment')->middleware('permission:finance.manage');
    Route::patch('invoices/{invoice}/status', [InvoiceController::class, 'status'])->name('invoices.status')->middleware('permission:finance.manage');
    Route::post('payments/{payment}/reverse', [InvoiceController::class, 'reversePayment'])->name('payments.reverse')->middleware('permission:finance.manage');
    Route::get('invoices/{invoice}/pdf', [DocumentController::class, 'invoice'])->name('invoices.pdf')->middleware('permission:finance.view');
    Route::resource('quotations', QuotationController::class)->only(['index', 'create', 'store', 'show'])->middleware('permission:finance.view');
    Route::post('quotations/{quotation}/convert', [QuotationController::class, 'convert'])->name('quotations.convert')->middleware('permission:finance.manage');
    Route::patch('quotations/{quotation}/status', [QuotationController::class, 'status'])->name('quotations.status')->middleware('permission:finance.manage');
    Route::get('quotations/{quotation}/pdf', [DocumentController::class, 'quotation'])->name('quotations.pdf')->middleware('permission:finance.view');
    Route::get('receipts/{receipt}/pdf', [DocumentController::class, 'receipt'])->name('receipts.pdf')->middleware('permission:finance.view');
    Route::resource('expenses', ExpenseController::class)->only(['index', 'store'])->middleware('permission:finance.view');
    Route::get('expenses/{expense}/receipt', [ExpenseController::class, 'receipt'])->name('expenses.receipt')->middleware('permission:finance.view');
    Route::resource('galleries', GalleryController::class)->middleware('permission:galleries.view');
    Route::get('gallery-links', [GalleryWorkflowController::class, 'links'])->name('galleries.links.index')->middleware('permission:galleries.manage');
    Route::post('galleries/{gallery}/photos', [GalleryController::class, 'upload'])->name('galleries.upload')->middleware('permission:galleries.manage');
    Route::get('galleries/{gallery}/photos/{photo}/preview', [GalleryController::class, 'preview'])->name('photos.preview')->middleware('permission:galleries.view');
    Route::get('galleries/{gallery}/photos/{photo}/download', [GalleryController::class, 'download'])->name('photos.download')->middleware('permission:galleries.view');
    Route::post('galleries/{gallery}/zip', [GalleryController::class, 'zip'])->name('galleries.zip')->middleware('permission:galleries.view');
    Route::get('galleries/{gallery}/workflow', [GalleryWorkflowController::class, 'selected'])->name('galleries.workflow')->middleware('permission:galleries.manage');
    Route::post('galleries/{gallery}/links', [GalleryWorkflowController::class, 'generate'])->name('galleries.links.generate')->middleware('permission:galleries.manage');
    Route::patch('gallery-links/{token}', [GalleryWorkflowController::class, 'token'])->name('galleries.links.update')->middleware('permission:galleries.manage');
    Route::post('galleries/{gallery}/reopen-selection', [GalleryWorkflowController::class, 'reopen'])->name('galleries.selection.reopen')->middleware('permission:galleries.manage');
    Route::post('galleries/{gallery}/editing', [GalleryWorkflowController::class, 'editing'])->name('galleries.editing')->middleware('permission:galleries.manage');
    Route::post('galleries/{gallery}/finals', [GalleryWorkflowController::class, 'uploadFinals'])->name('galleries.finals.upload')->middleware('permission:galleries.manage');
    Route::post('galleries/{gallery}/publish-final', [GalleryWorkflowController::class, 'publish'])->name('galleries.finals.publish')->middleware('permission:galleries.manage');
    Route::get('galleries/{gallery}/selected-originals', [GalleryWorkflowController::class, 'selectedZip'])->name('galleries.selected.zip')->middleware('permission:galleries.manage');
    Route::get('galleries/{gallery}/selected-originals/{photo}', [GalleryWorkflowController::class, 'selectedOriginal'])->name('galleries.selected.download')->middleware('permission:galleries.manage');
    Route::get('galleries/{gallery}/finals/{photo}/preview', [GalleryWorkflowController::class, 'finalPreview'])->name('galleries.finals.preview')->middleware('permission:galleries.manage');
    Route::get('galleries/{gallery}/qr', [GalleryController::class, 'qr'])->name('galleries.qr')->middleware('permission:galleries.view');
    Route::get('reports', [ReportController::class, 'index'])->name('reports.index')->middleware('permission:reports.view');
    Route::get('reports/csv', [ReportController::class, 'csv'])->name('reports.csv')->middleware('permission:reports.view');
    Route::get('reports/pdf', [DocumentController::class, 'report'])->name('reports.pdf')->middleware('permission:reports.view');
    Route::resource('tasks', TaskController::class)->only(['index', 'store', 'update'])->middleware('permission:bookings.view');
    Route::get('admin', [SuperAdminController::class, 'index'])->name('admin.index');
    Route::resource('admin/businesses', AdminBusinessController::class)->except('index')->names('admin.businesses');
    Route::patch('admin/businesses/{business}/storage', [AdminBusinessController::class, 'storage'])->name('admin.businesses.storage');
    Route::post('galleries/{gallery}/extend', [GalleryController::class, 'extend'])->name('galleries.extend')->middleware('permission:galleries.manage');
    Route::patch('admin/businesses/{business}/status', [SuperAdminController::class, 'status'])->name('admin.business.status');
    Route::get('admin/plans', [SuperAdminController::class, 'plans'])->name('admin.plans');
    Route::post('admin/plans', [SuperAdminController::class, 'plan'])->name('admin.plans.store');
    Route::patch('admin/plans/{plan}', [SuperAdminController::class, 'updatePlan'])->name('admin.plans.update');
    Route::get('admin/settings', [SuperAdminController::class, 'settings'])->name('admin.settings');
    Route::put('admin/settings', [SuperAdminController::class, 'updateSettings'])->name('admin.settings.update');
    Route::post('admin/notifications', [SuperAdminController::class, 'broadcast'])->name('admin.notifications');
    Route::post('admin/businesses/{id}/restore', [AdminBusinessController::class, 'restore'])->name('admin.businesses.restore');
    Route::post('admin/businesses/{business}/subscription', [SuperAdminController::class, 'subscribe'])->name('admin.business.subscription');
    Route::get('settings', [SettingsController::class, 'index'])->name('settings.index')->middleware('permission:settings.manage');
    Route::put('settings', [SettingsController::class, 'update'])->name('settings.update')->middleware('permission:settings.manage');
    Route::get('orders', [OperationsController::class, 'orders'])->name('orders.index')->middleware('permission:finance.view');
    Route::patch('orders/{order}', [OperationsController::class, 'orderStatus'])->name('orders.update')->middleware('permission:finance.manage');
    Route::post('orders/{order}/payments', [OperationsController::class, 'orderPayment'])->name('orders.payment')->middleware('permission:finance.manage');
    Route::get('print-orders', [OperationsController::class, 'prints'])->name('prints.index')->middleware('permission:finance.view');
    Route::post('print-orders', [OperationsController::class, 'printStore'])->name('prints.store')->middleware('permission:finance.manage');
    Route::patch('print-orders/{printOrder}', [OperationsController::class, 'printStatus'])->name('prints.update')->middleware('permission:finance.manage');
    Route::get('messages', [OperationsController::class, 'messages'])->name('messages.index')->middleware('permission:customers.view');
    Route::post('messages', [OperationsController::class, 'message'])->name('messages.store')->middleware('permission:customers.manage');
    Route::get('contracts', [OperationsController::class, 'contracts'])->name('contracts.index')->middleware('permission:customers.view');
    Route::post('contract-templates', [OperationsController::class, 'template'])->name('contracts.template')->middleware('permission:customers.manage');
    Route::post('contracts', [OperationsController::class, 'contract'])->name('contracts.store')->middleware('permission:customers.manage');
    Route::get('reviews', [OperationsController::class, 'reviews'])->name('reviews.index')->middleware('permission:customers.view');
    Route::patch('reviews/{review}', [OperationsController::class, 'review'])->name('reviews.update')->middleware('permission:customers.manage');
    Route::get('notifications', [NotificationController::class, 'index'])->name('notifications.index');
    Route::get('notifications/{notification}', [NotificationController::class, 'show'])->name('notifications.show');
    Route::post('notifications/read', [NotificationController::class, 'read'])->name('notifications.read');
    Route::get('portfolio', [PortfolioController::class, 'index'])->name('portfolio.index')->middleware('permission:galleries.manage');
    Route::post('portfolio/categories', [PortfolioController::class, 'category'])->name('portfolio.category')->middleware('permission:galleries.manage');
    Route::post('portfolio/photos', [PortfolioController::class, 'attach'])->name('portfolio.attach')->middleware('permission:galleries.manage');
    Route::post('support', [SupportController::class, 'store'])->name('support.store');
    Route::get('admin/support', [SupportController::class, 'index'])->name('admin.support');
    Route::patch('admin/support/{support}', [SupportController::class, 'update'])->name('admin.support.update');
});
