@extends('layouts.app')
@section('title',$gallery->exists?'Edit gallery':'New gallery')
@section('content')
<x-page-header :title="$gallery->exists?'Edit gallery':'New gallery'"/>
<form method="POST" action="{{ $gallery->exists?route('galleries.update',$gallery):route('galleries.store') }}" class="content-card">
@csrf @if($gallery->exists) @method('PUT') @endif
<div class="row g-3">
    <div class="col-lg-8"><label class="form-label">Gallery name</label><input name="name" value="{{ old('name',$gallery->name) }}" class="form-control" placeholder="Kelvin & Anna Wedding" required></div>
    <div class="col-lg-4"><label class="form-label">Customer <small class="text-muted">(optional for public/portfolio)</small></label><select name="customer_id" class="form-select"><option value="">No customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected(old('customer_id',$gallery->customer_id)==$customer->id)>{{ $customer->full_name }}</option>@endforeach</select></div>
    <div class="col-md-6"><label class="form-label">Booking (optional)</label><select name="booking_id" class="form-select"><option value="">None</option>@foreach($bookings as $booking)<option value="{{ $booking->id }}" @selected(old('booking_id',$gallery->booking_id)==$booking->id)>{{ $booking->booking_number }} · {{ $booking->customer->full_name }}</option>@endforeach</select></div>
    <div class="col-md-6"><label class="form-label">Shoot (optional)</label><select name="shoot_id" class="form-select"><option value="">None</option>@foreach($shoots as $shoot)<option value="{{ $shoot->id }}" @selected(old('shoot_id',$gallery->shoot_id)==$shoot->id)>{{ $shoot->shoot_number }} · {{ $shoot->customer->full_name }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">Gallery workflow</label><select name="type" class="form-select">@foreach(['final_delivery','selection','proof','final','public_event','private_event','portfolio'] as $type)<option value="{{ $type }}" @selected(old('type',$gallery->type)===$type)>{{ ['final_delivery'=>'Direct download ? send finished photos','selection'=>'Photo selection ? let the client choose'][$type] ?? str($type)->replace('_',' ')->title() }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">Access</label><select name="privacy" class="form-select">@foreach(['private'=>'Secure private link','pin'=>'Private link + PIN','customer'=>'Customer account','public'=>'Public gallery'] as $value=>$label)<option value="{{ $value }}" @selected(old('privacy',$gallery->privacy?:'private')===$value)>{{ $label }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">PIN</label><input name="pin" class="form-control" inputmode="numeric" autocomplete="new-password" placeholder="{{ $gallery->pin_hash?'Blank keeps current PIN':'Required for PIN access' }}"></div>
    <div class="col-md-4"><label class="form-label">Event name</label><input name="event" value="{{ old('event',$gallery->event) }}" class="form-control"></div>
    <div class="col-md-4"><label class="form-label">Event date</label><input name="event_date" type="date" value="{{ old('event_date',$gallery->event_date?->format('Y-m-d')) }}" class="form-control"></div>
    <div class="col-md-4"><label class="form-label">Gallery expiry</label><input name="expires_at" type="datetime-local" value="{{ old('expires_at',$gallery->expires_at?->format('Y-m-d\TH:i')) }}" class="form-control"><small class="text-muted">Default: 30 days. Extend this date to keep the gallery available longer.</small></div>
    <div class="col-12"><label class="form-label">Customer instructions</label><textarea name="description" class="form-control" rows="3" placeholder="A welcome message or instructions for your client.">{{ old('description',$gallery->description) }}</textarea></div>
    <div class="col-md-3"><label class="form-label">Selection limit (if used)</label><input name="selection_limit" type="number" min="1" value="{{ old('selection_limit',$gallery->selection_limit) }}" class="form-control"></div>
    <div class="col-md-3"><label class="form-label">Extra photo price</label><input name="extra_photo_price" type="number" min="0" step="0.01" value="{{ old('extra_photo_price',$gallery->extra_photo_price ?? 0) }}" class="form-control"></div>
    <div class="col-md-3"><label class="form-label">Public photo price</label><input name="photo_price" type="number" min="0" step="0.01" value="{{ old('photo_price',$gallery->photo_price ?? 0) }}" class="form-control"></div>
    <div class="col-md-3"><label class="form-label">Status</label><select name="status" class="form-select">@foreach(['draft','proofs_uploading','proofs_ready','selection_link_ready','selection_sent','customer_selecting','selection_submitted','selection_reopened','editing','final_upload_in_progress','final_ready','final_published','delivered','expired','archived'] as $status)<option value="{{ $status }}" @selected(old('status',$gallery->status?:'draft')===$status)>{{ str($status)->replace('_',' ')->title() }}</option>@endforeach</select></div>
    <div class="col-12 d-flex flex-wrap gap-4"><label><input type="checkbox" name="require_exact_selection" value="1" @checked(old('require_exact_selection',$gallery->require_exact_selection))> Require exact selection limit</label><label><input type="checkbox" name="watermark_enabled" value="1" @checked(old('watermark_enabled',$gallery->exists?$gallery->watermark_enabled:true))> Watermark proofs</label><label><input type="checkbox" name="downloads_enabled" value="1" @checked(old('downloads_enabled',$gallery->downloads_enabled))> Allow final downloads</label><label><input type="checkbox" name="payment_required" value="1" @checked(old('payment_required',$gallery->payment_required))> Require payment</label></div>
</div>
<button class="btn btn-primary mt-4">Save gallery</button>
</form>
@endsection
