@extends('layouts.app')
@section('title',$gallery->name)
@section('content')
<x-page-header :title="$gallery->name" :subtitle="$gallery->gallery_number"><div class="d-flex gap-2"><a class="btn btn-primary" href="{{ route('galleries.workflow',$gallery) }}">Selection & delivery</a><a class="btn btn-light" href="{{ route('galleries.edit',$gallery) }}">Edit</a><a class="btn btn-light" href="{{ route('galleries.qr',$gallery) }}">QR code</a></div></x-page-header>
<form id="photo-upload" enctype="multipart/form-data" method="POST" action="{{ route('galleries.upload',$gallery) }}" class="content-card mb-3">@csrf<div id="drop-zone" class="border border-2 border-dashed rounded p-4 text-center"><p>Drag photos here or choose files</p><input type="file" name="photos[]" accept="image/jpeg,image/png,image/webp" multiple required class="form-control"></div><label class="mt-2"><input type="checkbox" name="is_final" value="1"> Final high-resolution photos</label><div class="progress mt-2 d-none" id="upload-progress"><div class="progress-bar" style="width:0%">0%</div></div><button class="btn btn-primary mt-2">Upload and process</button></form>
@if($gallery->selection_completed_at)<div class="alert alert-danger"><strong>Customer selection submitted.</strong> Selected photos are marked in red below. Last submitted {{ $gallery->selection_completed_at->diffForHumans() }}.</div>@endif
<div class="row g-2">@foreach($photos as $photo)<div class="col-6 col-md-3"><div class="card h-100 {{ $photo->selections_count?'border border-danger border-3':'' }}"><img loading="lazy" class="card-img-top" src="{{ route('photos.preview',[$gallery,$photo]) }}"><div class="card-body"><small class="d-block text-truncate">{{ $photo->filename }}</small>@if($photo->selections_count)<span class="badge text-bg-danger">✓ CUSTOMER SELECTED</span>@else<span class="badge text-bg-light">Not selected</span>@endif <span class="badge text-bg-light">{{ $photo->favorites_count }} favorites</span>@if($photo->is_downloadable)<a href="{{ route('photos.download',[$gallery,$photo]) }}" class="btn btn-sm btn-light mt-2">Download</a>@endif</div></div></div>@endforeach</div>{{ $photos->links() }}<form method="POST" action="{{ route('galleries.destroy',$gallery) }}" class="mt-4">@csrf @method('DELETE')<button class="btn btn-outline-danger" onclick="return confirm('Archive this gallery?')">Archive gallery</button></form>
@endsection
@push('scripts')<script>const form=document.getElementById('photo-upload'),input=form.querySelector('input[type=file]'),zone=document.getElementById('drop-zone'),progress=document.getElementById('upload-progress'),bar=progress.querySelector('.progress-bar');['dragenter','dragover'].forEach(name=>zone.addEventListener(name,event=>{event.preventDefault();zone.classList.add('bg-light')}));['dragleave','drop'].forEach(name=>zone.addEventListener(name,event=>{event.preventDefault();zone.classList.remove('bg-light')}));zone.addEventListener('drop',event=>input.files=event.dataTransfer.files);form.addEventListener('submit',event=>{event.preventDefault();const request=new XMLHttpRequest();request.open('POST',form.action);request.setRequestHeader('X-Requested-With','XMLHttpRequest');request.upload.onprogress=e=>{if(e.lengthComputable){const percent=Math.round(e.loaded/e.total*100);progress.classList.remove('d-none');bar.style.width=percent+'%';bar.textContent=percent+'%'}};request.onload=()=>{if(request.status>=200&&request.status<400)location.reload();else{let message='Upload failed.';try{message=JSON.parse(request.responseText).message||message}catch(e){}alert(message)}};request.send(new FormData(form))});</script>@endpush
