@extends('layouts.app')
@section('title',$customer->full_name.' — PhotoHub')
@section('content')
<x-page-header :title="$customer->full_name" :subtitle="$customer->customer_number"><div class="d-flex gap-2"><a class="btn btn-outline-primary" href="{{ route('customers.edit',$customer) }}">Edit profile</a><a class="btn btn-primary" href="{{ route('bookings.create',['customer_id'=>$customer->id]) }}">New booking</a></div></x-page-header>
<div class="row g-4"><div class="col-lg-4"><div class="content-card auto-height"><h5>Contact details</h5><dl class="detail-list"><dt>Phone</dt><dd>{{ $customer->phone }}</dd><dt>Email</dt><dd>{{ $customer->email?:'—' }}</dd><dt>WhatsApp</dt><dd>{{ $customer->whatsapp?:'—' }}</dd><dt>Location</dt><dd>{{ collect([$customer->address,$customer->city,$customer->country])->filter()->join(', ')?:'—' }}</dd><dt>Status</dt><dd>{{ ucfirst($customer->status) }}</dd><dt>Portal</dt><dd>{{ $customer->user_id?'Enabled':'Not linked' }}</dd></dl><hr><h6>Internal notes</h6><p>{{ $customer->notes?:'No notes recorded.' }}</p></div></div>
<div class="col-lg-8"><div class="content-card"><ul class="nav nav-tabs" role="tablist">@foreach(['bookings'=>'Bookings','galleries'=>'Galleries','finance'=>'Finance','contracts'=>'Contracts','messages'=>'Messages','reviews'=>'Reviews'] as $key=>$label)<li class="nav-item"><button class="nav-link {{ $loop->first?'active':'' }}" data-bs-toggle="tab" data-bs-target="#{{ $key }}">{{ $label }}</button></li>@endforeach</ul><div class="tab-content pt-3">
<div class="tab-pane fade show active" id="bookings">@forelse($customer->bookings as $item)<a class="d-flex justify-content-between border-bottom py-2" href="{{ route('bookings.show',$item) }}"><span>{{ $item->booking_number }} · {{ $item->event_type }}</span><span>{{ $item->event_date->format('M j, Y') }}</span></a>@empty<p>No bookings.</p>@endforelse @foreach($customer->shoots as $shoot)<small class="badge text-bg-light">{{ $shoot->shoot_number }} · {{ str($shoot->status)->title() }}</small>@endforeach</div>
<div class="tab-pane fade" id="galleries">@forelse($customer->galleries as $item)<a class="d-flex justify-content-between border-bottom py-2" href="{{ route('galleries.show',$item) }}"><span>{{ $item->name }}</span><span>{{ str($item->status)->replace('_',' ')->title() }}</span></a>@empty<p>No galleries.</p>@endforelse</div>
<div class="tab-pane fade" id="finance"><h6>Invoices</h6>@forelse($customer->invoices as $item)<a class="d-flex justify-content-between py-2" href="{{ route('invoices.show',$item) }}"><span>{{ $item->invoice_number }}</span><span>Balance {{ number_format((float)$item->balance) }}</span></a>@empty<p>No invoices.</p>@endforelse<h6 class="mt-3">Quotations</h6>@foreach($customer->quotations as $item)<a class="d-block" href="{{ route('quotations.show',$item) }}">{{ $item->quotation_number }} · {{ number_format((float)$item->total) }}</a>@endforeach<h6 class="mt-3">Payments</h6>@foreach($customer->payments as $item)<p>{{ $item->payment_date->format('M j, Y') }} · {{ number_format((float)$item->amount) }} · {{ str($item->method)->replace('_',' ')->title() }}</p>@endforeach<h6>Photo orders</h6>@foreach($customer->orders as $item)<p>{{ $item->order_number }} · {{ number_format((float)$item->total) }} · {{ str($item->status)->title() }}</p>@endforeach</div>
<div class="tab-pane fade" id="contracts">@forelse($customer->contracts as $item)<p>Booking #{{ $item->booking_id }} · {{ str($item->status)->title() }} @if($item->accepted_at)<small>{{ $item->accepted_at->format('M j, Y') }}</small>@endif</p>@empty<p>No contracts.</p>@endforelse</div>
<div class="tab-pane fade" id="messages">@forelse($customer->messages->reverse() as $item)<div class="border-bottom py-2"><p class="mb-0">{{ $item->body }}</p><small>{{ $item->created_at->format('M j, H:i') }}</small></div>@empty<p>No messages.</p>@endforelse</div>
<div class="tab-pane fade" id="reviews">@forelse($customer->reviews as $item)<p><span class="text-warning">{{ str_repeat('★',$item->rating) }}</span> {{ $item->comment }}</p>@empty<p>No reviews.</p>@endforelse</div>
</div></div></div></div>
@endsection
