@extends('layouts.app')
@section('title','New quotation')
@section('content')
<x-page-header title="New quotation"/>
<form method="POST" action="{{ route('quotations.store') }}" class="content-card">@csrf
<div class="row g-2 mb-3"><div class="col-md-6"><label>Customer</label><select name="customer_id" class="form-select" required>@foreach($customers as $c)<option value="{{ $c->id }}" @selected(old('customer_id')==$c->id)>{{ $c->full_name }}</option>@endforeach</select></div><div class="col-md-6"><label>Related booking (optional)</label><select name="booking_id" class="form-select"><option value="">None</option>@foreach($bookings as $b)<option value="{{ $b->id }}" @selected(old('booking_id')==$b->id)>{{ $b->booking_number }} — {{ $b->customer->full_name }}</option>@endforeach</select></div></div>
<label>Quotation items</label><div id="items">@foreach(old('items',[['description'=>'','quantity'=>1,'unit_price'=>'']]) as $i=>$item)<div class="row g-2 item-row mb-2"><div class="col-md-6"><input name="items[{{ $i }}][description]" value="{{ $item['description'] }}" class="form-control" placeholder="Description" required></div><div class="col-md-2"><input name="items[{{ $i }}][quantity]" value="{{ $item['quantity'] }}" type="number" min=".01" step=".01" class="form-control" required></div><div class="col-md-3"><input name="items[{{ $i }}][unit_price]" value="{{ $item['unit_price'] }}" type="number" min="0" step=".01" class="form-control" placeholder="Unit price" required></div><div class="col-md-1"><button type="button" class="btn btn-outline-danger remove-item">×</button></div></div>@endforeach</div><button type="button" id="add-item" class="btn btn-sm btn-outline-secondary mb-3">Add item</button>
<div class="row g-2"><div class="col-md-3"><label>Date</label><input name="date" type="date" value="{{ old('date',today()->format('Y-m-d')) }}" class="form-control" required></div><div class="col-md-3"><label>Expiry</label><input name="expiry_date" type="date" value="{{ old('expiry_date',today()->addDays(14)->format('Y-m-d')) }}" class="form-control" required></div><div class="col-md-3"><label>Discount</label><input name="discount" value="{{ old('discount',0) }}" type="number" min="0" step=".01" class="form-control"></div><div class="col-md-3"><label>Tax</label><input name="tax" value="{{ old('tax',0) }}" type="number" min="0" step=".01" class="form-control"></div><div class="col-md-6"><label>Notes</label><textarea name="notes" class="form-control">{{ old('notes') }}</textarea></div><div class="col-md-6"><label>Terms</label><textarea name="terms" class="form-control">{{ old('terms') }}</textarea></div></div><button class="btn btn-primary mt-3">Create quotation</button></form>
<script>let itemIndex=document.querySelectorAll('.item-row').length;document.getElementById('add-item').onclick=()=>{document.getElementById('items').insertAdjacentHTML('beforeend',`<div class="row g-2 item-row mb-2"><div class="col-md-6"><input name="items[${itemIndex}][description]" class="form-control" placeholder="Description" required></div><div class="col-md-2"><input name="items[${itemIndex}][quantity]" value="1" type="number" min=".01" step=".01" class="form-control" required></div><div class="col-md-3"><input name="items[${itemIndex}][unit_price]" type="number" min="0" step=".01" class="form-control" placeholder="Unit price" required></div><div class="col-md-1"><button type="button" class="btn btn-outline-danger remove-item">×</button></div></div>`);itemIndex++};document.getElementById('items').onclick=e=>{if(e.target.classList.contains('remove-item')&&document.querySelectorAll('.item-row').length>1)e.target.closest('.item-row').remove()}</script>
@endsection
