<!doctype html><html><head><link rel="icon" type="image/png" href="{{ asset('favicon.png') }}"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>My PhotoHub portal</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="{{ asset('css/photohub.css') }}" rel="stylesheet"></head><body>
<nav class="navbar bg-white border-bottom"><div class="container"><span class="brand dark">PhotoHub</span><form method="POST" action="{{ route('logout') }}">@csrf<button class="btn btn-light">Sign out</button></form></div></nav>
<main class="container py-5">@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif<h1>Welcome, {{ $customer->full_name }}</h1>
<div class="row g-3 my-3">
    <div class="col-md-4"><div class="content-card"><h5>Bookings</h5>@forelse($bookings as $b)<p>{{ $b->event_type }} · {{ $b->event_date->format('M j, Y') }}</p>@empty<p>None yet.</p>@endforelse</div></div>
    <div class="col-md-4"><div class="content-card"><h5>Galleries</h5>@forelse($galleries as $g)<a class="d-block" href="{{ route('public.gallery',$g->code) }}">{{ $g->name }}</a>@empty<p>None yet.</p>@endforelse</div></div>
    <div class="col-md-4"><div class="content-card"><h5>Invoices</h5>@forelse($invoices as $i)<p>{{ $i->invoice_number }} · Balance {{ number_format((float)$i->balance) }}</p>@empty<p>None yet.</p>@endforelse</div></div>
</div>
<div class="row g-3 mb-3"><div class="col-md-4"><div class="content-card"><h5>Quotations</h5>@forelse($quotations as $quote)<p><a href="{{ route('portal.quotations.pdf',$quote) }}">{{ $quote->quotation_number }}</a> · {{ number_format((float)$quote->total) }} · {{ str($quote->status)->title() }}</p>@empty<p>None yet.</p>@endforelse</div></div><div class="col-md-4"><div class="content-card"><h5>Payments and receipts</h5>@forelse($payments as $payment)<p>{{ number_format((float)$payment->amount) }} · {{ str($payment->status)->title() }} @if($payment->receipt)<a href="{{ route('portal.receipts.pdf',$payment->receipt) }}">Receipt</a>@endif</p>@empty<p>None yet.</p>@endforelse</div></div><div class="col-md-4"><div class="content-card"><h5>Photo orders</h5>@forelse($orders as $order)<p>{{ $order->order_number }} · {{ number_format((float)$order->total) }} · {{ str($order->status)->replace('_',' ')->title() }}</p>@empty<p>None yet.</p>@endforelse</div></div></div>
@foreach($contracts->where('status','pending') as $c)<form method="POST" action="{{ route('portal.contracts.accept',$c) }}" class="content-card mb-3">@csrf<h5>Contract awaiting acceptance</h5><div class="border p-3 mb-2" style="white-space:pre-wrap">{{ $c->content }}</div><input name="accepted_name" class="form-control" placeholder="Your full name" required><label class="mt-2"><input type="checkbox" name="agree" value="1" required> I agree to this contract</label><button class="btn btn-primary d-block mt-2">Accept contract</button></form>@endforeach
<div class="row g-3"><div class="col-md-7"><div class="content-card"><h5>Conversation</h5>@forelse($messages->reverse() as $m)<div class="border-bottom py-2"><strong>{{ $m->sender_id===$customer->user_id?'You':'Studio' }}</strong><p class="mb-0">{{ $m->body }}</p><small>{{ $m->created_at->format('M j, H:i') }}</small></div>@empty<p>No messages yet.</p>@endforelse<form method="POST" action="{{ route('portal.message') }}" class="mt-3">@csrf<textarea name="body" class="form-control" placeholder="Message the studio" required></textarea><button class="btn btn-primary mt-2">Send</button></form></div></div>
<div class="col-md-5">@unless($hasReviewed)<form method="POST" action="{{ route('portal.review') }}" class="content-card">@csrf<h5>Review the studio</h5><select name="rating" class="form-select mb-2" required><option value="">Rating</option>@for($i=5;$i>=1;$i--)<option value="{{ $i }}">{{ $i }} stars</option>@endfor</select><textarea name="comment" class="form-control" placeholder="Your experience"></textarea><button class="btn btn-primary mt-2">Submit review</button></form>@else<div class="content-card">Thank you for sharing your review.</div>@endunless</div></div>
</main></body></html>
