@extends('layouts.app')
@section('title','Settings')
@section('content')
<x-page-header title="Business settings"/>
@include('settings.cloud-connection')
<x-storage-usage :business="$currentBusiness" compact />
<div class="content-card settings-plan mb-3">
    <div class="settings-plan-name"><h5 class="mb-0">{{ $usage['plan']?->name ?: 'No active plan' }}</h5>@if($usage['trial'])<span class="badge text-bg-light">Trial</span>@endif</div>
    <div class="settings-plan-meter">
        <div class="small mb-1">Galleries: {{ $usage['galleries'] }} / {{ $usage['plan']?->gallery_limit ?: 0 }}</div>
        <div class="progress" role="progressbar" aria-label="Gallery allowance used" aria-valuenow="{{ min(100,$usage['plan']?->gallery_limit?$usage['galleries']/$usage['plan']->gallery_limit*100:100) }}" aria-valuemin="0" aria-valuemax="100"><div class="progress-bar" style="width:{{ min(100,$usage['plan']?->gallery_limit?$usage['galleries']/$usage['plan']->gallery_limit*100:100) }}%"></div></div>
    </div>
</div>
<div class="row g-3"><div class="col-lg-8"><form enctype="multipart/form-data" method="POST" action="{{ route('settings.update') }}" class="content-card">@csrf @method('PUT')<h5>Profile and branding</h5><div class="row g-3"><div class="col-md-6"><label>Business name</label><input name="name" value="{{ old('name',$currentBusiness->name) }}" class="form-control" required></div><div class="col-md-6"><label>Email</label><input name="email" type="email" value="{{ old('email',$currentBusiness->email) }}" class="form-control" required></div><div class="col-md-6"><label>Phone</label><input name="phone" value="{{ old('phone',$currentBusiness->phone) }}" class="form-control"></div><div class="col-md-6"><label>Address</label><input name="address" value="{{ old('address',$currentBusiness->address) }}" class="form-control"></div><div class="col-md-6"><label>City</label><input name="city" value="{{ old('city',$currentBusiness->city) }}" class="form-control"></div><div class="col-md-6"><label>Country</label><input name="country" value="{{ old('country',$currentBusiness->country) }}" class="form-control"></div><div class="col-12"><label>About</label><textarea name="description" class="form-control">{{ old('description',$currentBusiness->description) }}</textarea></div><div class="col-md-6"><label>Currency</label><input name="currency" value="{{ $currentBusiness->currency }}" class="form-control" required></div><div class="col-md-6"><label>Timezone</label><input name="timezone" value="{{ $currentBusiness->timezone }}" class="form-control" required></div><div class="col-md-6"><label>Business logo</label><input name="logo" type="file" accept="image/*" class="form-control"></div><div class="col-md-6"><label>Watermark logo</label><input name="watermark_logo" type="file" accept="image/*" class="form-control"></div><div class="col-md-4"><label>Watermark text</label><input name="watermark_text" value="{{ data_get($settings,'watermark_text.value','PhotoHub') }}" class="form-control"></div><div class="col-md-4"><label>Opacity</label><input name="watermark_opacity" type="number" min="1" max="100" value="{{ data_get($settings,'watermark_opacity.value',50) }}" class="form-control" required></div><div class="col-md-4"><label>Position</label><select name="watermark_position" class="form-select">@foreach(['top_left','top_right','center','bottom_left','bottom_right'] as $position)<option value="{{ $position }}" @selected(data_get($settings,'watermark_position.value','bottom_right')===$position)>{{ str($position)->replace('_',' ')->title() }}</option>@endforeach</select></div><label><input type="checkbox" name="gallery_downloads" value="1" @checked(data_get($settings,'gallery_downloads.value'))> Enable gallery downloads by default</label><label><input type="checkbox" name="booking_deposit_required" value="1" @checked(data_get($settings,'booking_deposit_required.value'))> Require booking deposits</label></div><button class="btn btn-primary mt-3">Save settings</button></form></div>
<div class="col-lg-4"><form method="POST" action="{{ route('account.password') }}" class="content-card">@csrf @method('PUT')<h5>Change password</h5><input name="current_password" type="password" class="form-control mb-2" placeholder="Current password" required><input name="password" type="password" minlength="12" class="form-control mb-2" placeholder="New password" required><input name="password_confirmation" type="password" class="form-control" placeholder="Confirm new password" required><button class="btn btn-outline-primary mt-3">Change password</button></form></div></div>
@endsection
